# import = ["~/.config/alacritty/themes/nord.toml"]
import = ["~/.config/alacritty/themes/nvim-tokyo-moon.toml"]
# import = ["~/.config/alacritty/themes/cappuchin-mocha.toml"]
# import = ["~/.config/alacritty/themes/tokyo-night-storm.toml"]
# import = ["~/.config/alacritty/themes/tokyo-night.toml"]
# import = ["~/.config/alacritty/themes/mellow.toml"]
# import = ["~/.config/alacritty/themes/tokyo.toml"]



# [env]
# TERM = "xterm-256color"

[font]
# size = 14.0
# size = 18.0
size = 16
# size = 12.0

[font.offset]
# y=8
# y=24

[font.bold]
family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "GeistMono Nerd Font"
# family = "FiraCode Nerd Font Mono"
# family = "MonaspiceNe Nerd Font"
# family = "MonaspiceAr Nerd Font"
# family = "MonaspiceKr Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "GeistMono Nerd Font"
# family = "FiraCode Nerd Font Mono"
# family = "MonaspiceNe Nerd Font"
# family = "MonaspiceAr Nerd Font"
# family = "MonaspiceKr Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "GeistMono Nerd Font"
# family = "FiraCode Nerd Font Mono"
# family = "MonaspiceNe Nerd Font"
# family = "MonaspiceAr Nerd Font"
# family = "MonaspiceKr Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[window]
dynamic_padding = false
decorations = "full"
dynamic_title = false
opacity = 1
title = "👨‍💻"
option_as_alt = "OnlyLeft"

[window.padding]
x = 0
y = 0
