import = ["~/.config/alacritty/themes/nord.toml"]
# import = ["~/.config/alacritty/themes/cappuchin-mocha.toml"]
# import = ["~/.config/alacritty/themes/tokyo-night.toml"]
# import = ["~/.config/alacritty/themes/mellow.toml"]
# import = ["~/.config/alacritty/themes/tokyo.toml"]



[env]
TERM = "xterm-256color"

[font]
# size = 16.0
# size = 18.0
size = 16
# size = 12.0

[font.offset]
# y=32

[font.bold]
# family = "BlexMono Nerd Font Mono"
# family = "GeistMono Nerd Font"
family = "FiraCode Nerd Font Mono"
# family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
# family = "BlexMono Nerd Font Mono"
# family = "GeistMono Nerd Font"
family = "FiraCode Nerd Font Mono"
# family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "BlexMono Nerd Font Mono"
# family = "GeistMono Nerd Font"
family = "FiraCode Nerd Font Mono"
# family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
dynamic_title = false
opacity = 1
title = "👨‍💻"

[window.padding]
# x = 6
# y = 6
