#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Alacritty
rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

# Kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# https://gist.github.com/dhh/159b129f511f76db3ae8adb463f70d05
# zellij
rm -rf $HOME/.config/zellij
ln -sf $DOTFILES/zellij $HOME/.config/zellij
