[settings]
legacy_version_file = true

[settings.ruby]
compile = false

[tools]
atuin = "latest"
bun = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
lazydocker = "latest"
node = "lts"
"ubi:adwinying/php" = "8.3.30"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
zoxide = "latest"
