[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

# [colors.primary]
# background = "0x30363d"
# foreground = "0xe6edf3"

# [colors.cursor]
# text = "0x30363d"
# cursor = "0xe6edf3"

# [colors.normal]
# black = "0x484f58"
# red = "0xff7b72"
# green = "0x3fb950"
# yellow = "0xd29922"
# blue = "0x58a6ff"
# magenta = "0xbc8cff"
# cyan = "0x39c5cf"
# white = "0xb1bac4"

# [colors.bright]
# black = "0x6e7681"
# red = "0xffa198"
# green = "0x56d364"
# yellow = "0xe3b341"
# blue = "0x79c0ff"
# magenta = "0xbc8cff"
# cyan = "0x39c5cf"
# white = "0xb1bac4"
